### ISSUE TITLE
isAnimated option for v3?

### ISSUE THREAD

**Issue by manoj382** [desandro/masonry-docs#30]
Is there a way with version 3 to animate the grid container when resizing or when new grid items are appended? There was a way in version 2 [http://desandro.github.io/masonry/demos/animating-jquery.html], but I can't figure out a way to do it with v3. Thanks!

**Comment by desandro** [comment]
You can set transition style on the grid container. See demo http://codepen.io/desandro/pen/JYWKpj

``` css
.grid {
  -webkit-transition: height 0.4s;
          transition: height 0.4s;
}
```
